### ISSUE TITLE
请问我当前的老项目使用的是jq，代码量很庞大，现在我想在这个项目中使用ofa.js，出现命名冲突该怎么办

### ISSUE THREAD

**Issue by faith1605** [kirakiray/ofa.js#103]
ofa.js中有类似jq的jQuery.noConflict()方法可以重命名$吗，毕竟老代码，我去改原先jq用到的$也不太现实

**Comment by kirakiray** [comment]
我给你支个招，按照如下进行初始化：

```html
<script src="xxxx/ofa.min.js"></script> <!-- 1. 先引用 ofa.js -->
<script>
// 2. 替换掉 $
window.ofa = window.$;
delete window.$;
</script>
```
<script src="xxxx/jquery.min.js"></script> 

这样你就可以用 ofa变量来替代原来初始化的 $。

**Comment by faith1605** [comment]
> 我给你支个招，按照如下进行初始化：
> 
> ```
> <script src="xxxx/ofa.min.js"></script> 
> <script>
> // 2. 替换掉 $
> window.ofa = window.$;
> delete window.$;
> </script>
> <script src="xxxx/jquery.min.js"></script> 
> ```
> 
> 这样你就可以用 ofa变量来替代原来初始化的 $，就不会和jQuery冲突了。
> 
> 但这个方案还没实验过，如果发生了问题可以反馈到这里。

有问题的，虽然替换了变量名，但是lm组件没办法识别

**Comment by kirakiray** [comment]
> 
> 有问题的，虽然替换了变量名，但是lm组件没办法识别

刚刚更新了一个版本，试一下

https://github.com/kirakiray/ofa.js/releases/tag/4.3.39

**Comment by faith1605** [comment]
> 我给你支个招，按照如下进行初始化：
> 
> ```
> <script src="xxxx/ofa.min.js"></script> 
> <script>
> // 2. 替换掉 $
> window.ofa = window.$;
> delete window.$;
> </script>
> <script src="xxxx/jquery.min.js"></script> 
> ```
> 
> 这样你就可以用 ofa变量来替代原来初始化的 $，就不会和jQuery冲突了。
> 
> 但这个方案还没实验过，如果发生了问题可以反馈到这里。

我刚刚用了4.3.39版本，不会报错了，不过还是没有正确编译出来组件的内容
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>使用ofa</title>
  <script src="ofa.min.js"></script>
  <script>
    window.ofa = window.$;
    delete window.$
  </script>
  <script src="jq.js"></script>
  <style>
    my-switch::part(switch-box) {
      background-color: red;
    }
  </style>
</head>
<body>
  <l-m src="./components/switch/switch.html"></l-m>
  <my-switch></my-switch>
</body>
</html>
这是我的demo代码，是不是哪里写的有问题呀

**Comment by faith1605** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>使用ofa</title>
  <script src="ofa.min.js"></script>
  <script>
    window.ofa = window.$;
    delete window.$
  </script>
  <script src="jq.js"></script>
  <l-m src="./components/switch/switch.html"></l-m>
  <style>
    my-switch::part(switch-box) {
      background-color: red;
    }
  </style>
</head>
<body>
  <my-switch></my-switch>
</body>
</html>

**Comment by faith1605** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>使用ofa</title>
  <script src="ofa.min.js"></script>
  <script>
    window.ofa = window.$;
    delete window.$
  </script>
  <script src="jq.js"></script>
  <l-m src="./components/switch/switch.html"></l-m>
  <style>
    my-switch::part(switch-box) {
      background-color: red;
    }
  </style>
</head>
<body>
  <my-switch></my-switch>
</body>
</html>`

**Comment by kirakiray** [comment]
刚刚试了下，好像标识器还有点问题，在加一个步骤：

```html
<!-- 1. 先引用 ofa.js -->
    <script src="xxx/ofa.min.js"></script>
    <script>
      // 2. 替换掉 $
      window.ofa = window.$;
      delete window.$;
    </script>
    <!-- 3. 初始化 jquery -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <!-- 4.替换回标识器 -->
    <script>
      $.COMP = ofa.COMP;
      $.PAGE = ofa.PAGE;
    </script>
```

**Comment by kirakiray** [comment]
> ![image](https://private-user-images.githubusercontent.com/54224172/285735697-6d3d1514-4e41-4b21-9630-1abf297a8736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjUyNTksIm5iZiI6MTcwMTA2NDk1OSwicGF0aCI6Ii81NDIyNDE3Mi8yODU3MzU2OTctNmQzZDE1MTQtNGU0MS00YjIxLTk2MzAtMWFiZjI5N2E4NzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2MDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMjdlNzI2MjdhN2RmYjYyZTMzNmVmMGNkOWJmYzUzYzllZTE3YTVlYmE3ODA1MWVjNmUzYTcxNjA1N2UxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zougq5ZCQQ0Y_kDcABFQ-V8sCkzrwQP0PT26bIvF9L4)

没有问题

**Comment by faith1605** [comment]
> 我今晚在加个 noConflict 方法发版，到时候就可以把上面的步骤去掉了。现在我看看有没有更好的方案再动手。

嗯嗯，非常感谢，我还想问一个问题，就是例如这个switch组件代码的class是checked是动态修改的，我如何在外部这个页面去自定义这个checked类的样式呢，我尝试了给part动态增加checked，不过失败了，请问这个情况你有遇到吗

**Comment by faith1605** [comment]
> > 我今晚在加个 noConflict 方法发版，到时候就可以把上面的步骤去掉了。现在我看看有没有更好的方案再动手。
> 
> 嗯嗯，非常感谢，我还想问一个问题，就是例如这个switch组件代码的class是checked是动态修改的，我如何在外部这个页面去自定义这个checked类的样式呢，我尝试了给part动态增加checked，不过失败了，请问这个情况你有遇到吗

![image](https://github.com/kirakiray/ofa.js/assets/54224172/3280686f-a77e-44b4-83f8-b2895cefc191)
这个问题我使用外部引入link解决了，同时利用组件的生命周期，确保可以正确的在组件渲染后确实挂载了shadowDOM之后再进行引入。
你觉得这个方法是比较好的吗，因为如果用我这个方法的话现在又引申出了一个新的问题，就是如果我一个页面同时使用多个组件，我可能需要把这个逻辑写一个循环，然后给每一个组件都引入这个公用的css，感觉也有点说不出来的感觉
你觉得可行吗或者你觉得还有没有什么更好的方法可以处理这个问题呀，因为我不知道如何在主页面出直接使用css进行修改所以才采用的这种方式来处理的

**Comment by kirakiray** [comment]
> > 我今晚在加个 noConflict 方法发版，到时候就可以把上面的步骤去掉了。现在我看看有没有更好的方案再动手。
> 
> 嗯嗯，非常感谢，我还想问一个问题，就是例如这个switch组件代码的class是checked是动态修改的，我如何在外部这个页面去自定义这个checked类的样式呢，我尝试了给part动态增加checked，不过失败了，请问这个情况你有遇到吗

这个组件的相关代码方便我看看吗？`part="switch-box"` 这个元素的样式应该是可以生效的。

> 这个问题我使用外部引入link解决了，同时利用组件的生命周期，确保可以正确的在组件渲染后确实挂载了shadowDOM之后再进行引入。

封装组件的意义就是减少逻辑代码，如果是通过插入link修改样式，可以考虑下是否需要将这种样式修改，封装成一个属性来切换。例如：

```javascript
export default {
  ...,
  attrs:{
    uimode:"bootstrap"
  }
  ...
};
```

**Comment by kirakiray** [comment]
添加了一章和 jQuery 共存的文章：https://ofajs.com/cn/docs/others/coexist-with-jquery.html

**Comment by faith1605** [comment]
> > > 我今晚在加个 noConflict 方法发版，到时候就可以把上面的步骤去掉了。现在我看看有没有更好的方案再动手。
> > 
> > 
> > 嗯嗯，非常感谢，我还想问一个问题，就是例如这个switch组件代码的class是checked是动态修改的，我如何在外部这个页面去自定义这个checked类的样式呢，我尝试了给part动态增加checked，不过失败了，请问这个情况你有遇到吗
> 
> 这个组件的相关代码方便我看看吗？`part="switch-box"` 这个元素的样式应该是可以生效的。
> 
> > 这个问题我使用外部引入link解决了，同时利用组件的生命周期，确保可以正确的在组件渲染后确实挂载了shadowDOM之后再进行引入。
> 
> 封装组件的意义就是减少逻辑代码，如果是通过插入link修改样式，可以考虑下是否需要将这种样式修改，封装成一个属性来切换。例如：
> 
> ```js
> export default {
>   ...,
>   attrs:{
>     uimode:"bootstrap"  // 没有太理解这样做如何在外部可以定义组件内某个元素的动态样式，可以帮忙写一个示例看一下吗
>   }
>   ...
> };
> ```
> 
> 真正更改样式的时候，就通过修改组件的 `uimode` （可以改其他名）属性，来切换到自己想要的样式。

![image](https://github.com/kirakiray/ofa.js/assets/54224172/2fabf20a-1d9c-4d33-8f69-bbcf2e6fe6ce)
这个是switch组件的代码，其实就是官网给到的switch Demo
目前我遇到的问题是没办法在外部定义组件内部某个元素的动态样式，我只能改定义了part的元素，但是动态绑定的class
我改不了，我一开始想的是动态绑定part，但是不知道ofa.js支持这个方式吗，因为我尝试了很多方式，没有成功，例如:name="key"，是直接报错的
![image](https://github.com/kirakiray/ofa.js/assets/54224172/1ebcd431-e704-4217-a403-5465bb29f540)

**Comment by kirakiray** [comment]
> 目前我遇到的问题是没办法在外部定义组件内部某个元素的动态样式，我只能改定义了part的元素，但是动态绑定的class
我改不了，我一开始想的是动态绑定part，但是不知道ofa.js支持这个方式吗，因为我尝试了很多方式，没有成功，例如:name="key"，是直接报错的

`:part="checked"` 这种语法是改了实例属性 part 的值。应该是改 attributes，所以要改成 `attr:part="checked"`。

**Comment by faith1605** [comment]
> attr:part="checked"

嗯嗯，解决了，非常感谢
