### ISSUE TITLE
路过

### ISSUE THREAD

**Issue by kajweb** [kirakiray/ofa.js#11]
Vue、react应该支持直接通过CDN引入。请问相比之下，您的优势在哪？

**Comment by kirakiray** [comment]
sorry，最近比较忙，现在才看到。

Vue 和 React 直接引入的方式下，没办法做工程化构建；

ofajs 内部集成了一个微型工程化框架（模块化，组件化和文件处理等操作），引用即包含工程化的功能，所以，能很轻易的使用 ofajs 的成果；

比如基于 ofajs 开发的电子书应用 [o-book](https://kirakiray.github.io/o-book/website/)，直接引用一个标签，就能制作电子书网页；直接引用 Vue 和 React 很难做到这点；

从原理上，Vue 和 React （等其它框架）的设计逻辑，是让代码编译为浏览器支持的格式；ofajs的设计逻辑，是让浏览器直接支持这些代码；

**Comment by makai1027** [comment]
> sorry，最近比较忙，现在才看到。
> 
> Vue 和 React 直接引入的方式下，没办法做工程化构建；
> 
> ofajs 内部集成了一个微型工程化框架（模块化，组件化和文件处理等操作），引用即包含工程化的功能，所以，能很轻易的使用 ofajs 的成果；
> 
> 比如基于 ofajs 开发的电子书应用 [o-book](https://kirakiray.github.io/o-book/website/)，直接引用一个标签，就能制作电子书网页；直接引用 Vue 和 React 很难做到这点；
> 
> 从原理上，Vue 和 React （等其它框架）的设计逻辑，是让代码编译为浏览器支持的格式；ofajs的设计逻辑，是让浏览器直接支持这些代码；

我觉得你应该把对比优势写在首页上，除了你说的直接引用，例如代码体积、运行速度、生态建设等等

**Comment by kirakiray** [comment]
> > sorry，最近比较忙，现在才看到。
> > Vue 和 React 直接引入的方式下，没办法做工程化构建；
> > ofajs 内部集成了一个微型工程化框架（模块化，组件化和文件处理等操作），引用即包含工程化的功能，所以，能很轻易的使用 ofajs 的成果；
> > 比如基于 ofajs 开发的电子书应用 [o-book](https://kirakiray.github.io/o-book/website/)，直接引用一个标签，就能制作电子书网页；直接引用 Vue 和 React 很难做到这点；
> > 从原理上，Vue 和 React （等其它框架）的设计逻辑，是让代码编译为浏览器支持的格式；ofajs的设计逻辑，是让浏览器直接支持这些代码；
> 
> 我觉得你应该把对比优势写在首页上，除了你说的直接引用，例如代码体积、运行速度、生态建设等等

感谢你的反馈
