### ISSUE TITLE
无界微前端框架配合ofa.js

### ISSUE THREAD

**Issue by moxia** [kirakiray/ofa.js#112]
从官网下载的启动项目作为无界子应用，发现页面加载不出来，请问ofa.js支持接入无界么？

**Comment by kirakiray** [comment]
没用过无界，其实不需要用无界也是可以直接使用 ofa.js 的，这里有两个案例

https://github.com/ofajs/ofa.js-in-react

https://github.com/ofajs/ofajs-in-vue3

我理解无界应该是个隔离容器，它的底层逻辑可能要搭配路由来用，所以你试试搭配路由试试：https://ofajs.com/cn/cases/use-hash-router.html

我周五试试无界搭配 ofa.js。

**Comment by frmachao** [comment]
![image](https://github.com/kirakiray/ofa.js/assets/22849231/dc1e85e3-795e-440d-b96f-64ead09399f6)
wuji 是把子应用中的 js 资源文件抽出来，然后重新创建 script 标签，并插入到 iframe 的 head 中。但是 子应用是渲染在 web component 中。可能因为这个原因倒是，ofa.js 没有被正确的作用到，子应用所在的 dom root。
让 ofa.js 在 wuji 中 work ，还需要再探索一下。
