### ISSUE TITLE
Does ofa.js have compute properties or does ofa.js support add calculation method?

### ISSUE THREAD

**Issue by mwxxhdb** [kirakiray/ofa.js#115]
Does ofa.js have compute properties?
Or can I add a calculation method?
For example, the attribute is a list, and when rendering the list, color of each item is calculated based on its attribute.
Because there is a lot of calculation logic, it will be very long code to put it in the HTML attribute field.

```html
<my-list :list="todoList"></my-list>

<!--- my-list.html --->
<x-fill :value="list">
    <p :class="calculateClass($data)"></p>
</x-fill>
```

**Comment by kirakiray** [comment]
Yes, the calculation method is on $host, just add $host in front of it.

```html
<my-list :list="todoList"></my-list>

<!--- my-list.html --->
<x-fill :value="list">
    <p :class="calculateClass($data)"></p>
</x-fill>

<script>
export default {
  tag:"xxx-xxx",
  proto:{
    calculateClass(data){
      // code
    }
  }
};
</script>
```
