### ISSUE TITLE
x-fill中绑定事件异常

### ISSUE THREAD

**Issue by itmanyong** [kirakiray/ofa.js#118]
以下几种绑定方式都行不通，对于代码和报错如下截图
第一种
![image](https://github.com/kirakiray/ofa.js/assets/53500371/f319533d-9daa-4911-9ec5-de176bfbec58)
![image](https://github.com/kirakiray/ofa.js/assets/53500371/b3cc988c-b52d-4888-a34d-ed68e9b98888)

第二种
![image](https://github.com/kirakiray/ofa.js/assets/53500371/486c078e-cd11-429e-8cb8-61c413d7a584)
![image](https://github.com/kirakiray/ofa.js/assets/53500371/29fcfff1-1b93-4f05-8785-63d2d64ec7c9)

**Comment by kirakiray** [comment]
x-fill 内属于的 this 指向 $data 本身，toJump 方法在 host 上，所以要改成 `on:click="$host.toJump()"`

https://ofajs.com/cn/cases/fill.html

**Comment by kirakiray** [comment]
这个案例中还带上了event，所以要改成 `on:click="$host.toJump($event)"`。（不好意思，才发现 $event 在文档内，晚点补）

**Comment by itmanyong** [comment]
> 这个案例中还带上了event，所以要改成 `on:click="$host.toJump($event)"`。（不好意思，才发现 $event 没在文档内，晚点补）

建议文档可以新开一栏用以放置这类容易忽略较为隐蔽的功能设计点
