### ISSUE TITLE
有没有什么方式可以使组件内的可以受到外部样式的影响

### ISSUE THREAD

**Issue by itmanyong** [kirakiray/ofa.js#119]
1.比如全局css，组件内部想要直接使用就很不方便。有没有很优雅的方式

**Comment by kirakiray** [comment]
组件封装的本质就是做隔离；如果想要改动组件内的部分样式，是web components 的知识点，大致为如下操作：

1. 使用 `::part` 修改组件内部容器

https://developer.mozilla.org/en-US/docs/Web/CSS/::part

https://github.com/kirakiray/ofa.js/issues/100#issuecomment-1820692382

2. 组件内可以沿用css变量

https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_custom_properties

```html
<!--my-comp.html-->
<div style="background-color:var(--inner-color,blue)"></div>. <!--使用 inner-color，如果没有，则为 blue-->
```

```html
<my-comp style="--inner-color:red;"></my-comp>
```

3. 组件内部提前定义属性对应的样式：

```html
<!--my-comp.html-->
<style>
:host([sc='red']) .container{
  color:red;
}
</style>
<div class="container">In container</div>
```

```html
<my-comp sc="red"></my-comp>
```

**Comment by kirakiray** [comment]
还有一个比较少用的情况，直接通过 shadow 访问内部节点并修改 style，但是这样只适合修改少量样式，而且并不建议：

```html
<!--my-comp.html-->
<div class="container">In container</div>
```

```javascript
```

**Comment by itmanyong** [comment]
看来ofa没有对这块做针对性处理。想实现的是类似于我全局引入了layui.css，但是在组件内部无法直接使用其定义的样式，不会生效。目前采用的方式是在组件内的style标签内通过@import方式引入可以生效

**Comment by kirakiray** [comment]
> 看来ofa没有对这块做针对性处理。想实现的是类似于我全局引入了layui.css，但是在组件内部无法直接使用其定义的样式，不会生效。目前采用的方式是在组件内的style标签内通过@import方式引入可以生效

是的如楼上所说，在每个需要使用layui.css的组件内，用 link标签引用一次这个样式文件。
