### ISSUE TITLE
How to know whether the default slot has child?

### ISSUE THREAD

**Issue by mwxxhdb** [kirakiray/ofa.js#120]
`parent.html`
```html
<style>
  .container {
    border: 1px solid red;
  }
  .container.has-child {
    border: 1px solid blue;
  }
</style>
<div class="container">
  <slot></slot>
</div>
```

`child.html`
```html
<v-parent></v-parent>
<v-parent>
  <v-child></v-child>
</v-parent>
```

I'd like to change some styles of v-parent component when it detected there is v-child in its default slot.

**Comment by kirakiray** [comment]
You can use the has() selector with [inject-host](https://ofajs.com/cn/cases/inject-host.html), but this API is relatively new, please use it as appropriate; For example, in the following component, if there is a p tag inside, it will use a blue border:


```html
<template component>
  <style>
    :host {
      display: block;
    }
    .container {
      border: 1px solid red;
    }
  </style>
  <inject-host>
    <style>
      my-comp:has(p)::part(container) {
        border: 1px solid blue;
      }
    </style>
  </inject-host>
  <div class="container" part="container">
    <slot></slot>
  </div>
</template>
```

https://developer.mozilla.org/zh-CN/docs/Web/CSS/:has

https://caniuse.com/?search=%3Ahas

https://ofajs.com/cn/cases/inject-host.html

If you want better compatibility, you can use [slotchange](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event), such as the following component, if there is a p tag inside , just use the blue border:

```html
<template component>
  <style>
    :host {
      display: block;
    }
    .container {
      border: 1px solid red;
    }
    .container.has-p {
      border: 1px solid blue;
    }
  </style>
  <div class="container" class:has-p="hasP" part="container">
    <slot></slot>
  </div>
  <script>
    export default {
      tag: "my-comp",
      data: {
        hasP: false,
      },
      ready() {
        this.shadow.on("slotchange", () => {
          this.hasP = !!this.$("p");
        });
      },
    };
  </script>
</template>
```

**Comment by kirakiray** [comment]
Sorry, I seem to have read the wrong case. If you just want to distinguish whether there is filler, you only need to use [:host()](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:host_function) and [:empty](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:empty) together:

```html
<template component>
  <style>
    :host {
      display: block;
    }
    .container {
      border: 1px solid blue;
      min-height: 30px;
    }
    :host(:empty) .container {
      border: 1px solid red;
    }
  </style>
  <div class="container">
    <slot></slot>
  </div>
</template>
```

In this component, the default border without content is red, and it turns blue when filled with content.
