### ISSUE TITLE
ofa组件/页面内有无引入外部js的相关方案

### ISSUE THREAD

**Issue by itmanyong** [kirakiray/ofa.js#121]
1.主要处理的场景在于例如一些外部库的js，其内含有一些自执行逻辑作用于dom。例如layui.js，使用select组件时无法正常初始化，尝试过想到的处理方式均未生效

**Comment by kirakiray** [comment]
ofa.js 是使用web components 封装的容器，与外部隔离了dom，所以会导致这部分逻辑无法生效。需要将初始化的逻辑从 document 切换到 shadow root上；

例如 layui 的表单组件，就是将这里改为指定的shadow root：https://github.com/layui/layui/blob/4af994d21897c5bbca08bb293f572e7226cea3f6/src/modules/form.js#L1092

时间有限，我并没有翻到关于layui更改初始化容器的逻辑。如果后续有充裕手段，可能才会花点时间去看看。目前组件内可以通过 import 或者 load 运行另一个js文件。
