### ISSUE TITLE
bind click event error

### ISSUE THREAD

**Issue by fightwithtiger** [kirakiray/ofa.js#128]
demo-comp.html

```html
<template component>
	<x-fill :value="counts">
{{$host}}

		<!-- how to excute changeVal method, get error: Uncaught TypeError: Cannot read properties of undefined (reading '#<PointerEvent>') -->
		<!-- <button on:click="$host.proto.changeVal">add</button> -->
		
		<!-- I don't known how to excute changeVal method with current index -->
		<!-- <button on:click="() => $host.changeVal($index)">add</button> -->
		<div class="item">$index : {{$index}}; $data : {{$data}}</div>
	</x-fill>
	<script>
		export default {
			data: {
				counts: [0, 0, 0],
			},
			proto: {
				changeVal(idx) {
					this.counts[idx] += 1
				},
			},
		};
	</script>
</template>
```

Theres are two problems:
1. how to excute changeVal method in x-fill
2. how to excute method with dynamic params

**Comment by kirakiray** [comment]
Change it to `on:click="$host.changeVal($index)"`

**Comment by kirakiray** [comment]
```html
<template component>
  <x-fill :value="counts">
    {{$host}}
    <div class="item" on:click="$host.changeVal($index)">
      $index : {{$index}}; $data : {{$data}}
    </div>
  </x-fill>
  <script>
    export default {
      data: {
        counts: [0, 0, 0],
      },
      proto: {
        changeVal(idx) {
          this.counts[idx] += 1;
        },
      },
    };
  </script>
</template>

```

**Comment by kirakiray** [comment]
Within fill:
$host represents the host component;
$index represents index;
$data represents filled data items;
$event represents the native event object;

https://ofajs.com/en/cases/fill.html

**Comment by fightwithtiger** [comment]
> 将其更改为`on:click="$host.changeVal($index)"`

Thanks, but this appears to be an execution of a function rather than a binding event to onclick. Consider compatibility with the grammar: on:click="() => $host.changeVal(${index})"

**Comment by kirakiray** [comment]
> Thanks, but this appears to be an execution of a function rather than a binding event to onclick. Consider compatibility with the grammar: `on:click="() => $host.changeVal($index)"`

You can directly fill in the function on the host for binding. as follows:
`on:click="$host.changeVal"`

However, it should be noted that at this time, the this of the function on the component will point to the fill item itself. You can try the code:

```html
<template component>
  <x-fill :value="counts">
    {{$host}}
    <div class="item" on:click="$host.changeVal">
      $index : {{$index}}; $data : {{$data}}
    </div>
  </x-fill>
  <script>
    export default {
      data: {
        counts: [0, 0, 0],
      },
      proto: {
        changeVal() {
          //   this.counts[idx] += 1;
          console.log(this);
          this.$host.counts[this.$index] = this.$host.counts[this.$index] + 1;
        },
      },
    };
  </script>
</template>
```

**Comment by fightwithtiger** [comment]
> > Thanks, but this appears to be an execution of a function rather than a binding event to onclick. Consider compatibility with the grammar: `on:click="() => $host.changeVal($index)"`
> 
> You can directly fill in the function on the host for binding. as follows: `on:click="$host.changeVal"`
> 
> However, it should be noted that at this time, the this of the function on the component will point to the fill item itself. You can try the code:
> 
> ```
> <template component>
>   <x-fill :value="counts">
>     {{$host}}
>     <div class="item" on:click="$host.changeVal">
>       $index : {{$index}}; $data : {{$data}}
>     </div>
>   </x-fill>
>   <script>
>     export default {
>       data: {
>         counts: [0, 0, 0],
>       },
>       proto: {
>         changeVal() {
>           //   this.counts[idx] += 1;
>           console.log(this);
>           this.$host.counts[this.$index] = this.$host.counts[this.$index] + 1;
>         },
>       },
>     };
>   </script>
> </template>
> ```

But, I don't think it's a good way to use $index in the proto's method, for example:
```
<template component>
	<x-fill :value="counts">
		<div class="item" on:click="$host.changeVal">
			$index : {{$index}}; $data : {{$data}}
		</div>
	</x-fill>

	<br />
	<br />

	<x-fill :value="counts">
		<div class="item" on:click="$host.changeVal2">
			$index2 : {{$index}}; $data2 : {{$data}}
		</div>
	</x-fill>
	<script>
		export default {
			data: {
				counts: [0, 0, 0],
				counts2: [0, 0, 0],
			},
			proto: {
				changeVal() {
					// const currentIndex = this.$index
					setTimeout(() => {
						// this.$host.counts[currentIndex] = this.$host.counts[currentIndex] + 1;
						this.$host.counts[this.$index] = this.$host.counts[this.$index] + 1;
					}, 2000)
				},
				changeVal2() {
					this.$host.counts[this.$index] = this.$host.counts[this.$index] + 1;
				},
			}
		};
	</script>
</template>
```

Althought I got $index from this, but I have two x-fill tags. This means I need two separate x-fill info($index, $data), when I click the first x-fill div and the second one in two seconds , I got wrong $index in settimeout method. I have to use currentIndex to save the initial value, I might as well just pass in the parameters, that seems like a big mental burden !

**Comment by kirakiray** [comment]
In fact, it is not recommended to directly bind the host function in the fill item. If you want to bind, you must first obtain '$index' and '$data', reducing the use of 'this', so that the code is more concise and intuitive.

```html
<template component>
  <x-fill :value="counts">
    <div class="item" on:click="$host.changeVal">
      $index : {{$index}}; $data : {{$data}}
    </div>
  </x-fill>

  <br />
  <br />

  <x-fill :value="counts">
    <div class="item" on:click="$host.changeVal2">
      $index2 : {{$index}}; $data2 : {{$data}}
    </div>
  </x-fill>
  <script>
    export default {
      data: {
        counts: [0, 0, 0],
        counts2: [0, 0, 0],
      },
      proto: {
        changeVal() {
          // const currentIndex = this.$index
          //   console.log(this);
          const { $index, $host } = this;

          setTimeout(() => {
            console.log();
            // this.$host.counts[currentIndex] = this.$host.counts[currentIndex] + 1;
            $host.counts[$index] = $host.counts[$index] + 1;
          }, 200);
        },
        changeVal2() {
          const { $index, $host } = this;
          $host.counts[$index] = $host.counts[$index] + 1;
          //   this.$host.counts[this.$index] = this.$host.counts[this.$index] + 1;
        },
      },
    };
  </script>
</template>

```

**Comment by kirakiray** [comment]
This case may be a little off. Usually when using the fill component, the filled list content is object data; at this time, it is more intuitive to directly update the data on the list items.

```html
<template component>
  <x-fill :value="counts">
    <div class="item" on:click="$data.val++">
      $index : {{$index}}; $data : {{$data.val}}
    </div>
  </x-fill>

  <br />
  <br />

  <x-fill :value="counts">
    <div class="item" on:click="$host.changeVal">
      $index2 : {{$index}}; $data2 : {{$data}}
    </div>
  </x-fill>
  <script>
    export default {
      data: {
        counts: [{ val: 0 }, { val: 0 }, { val: 0 }],
      },
      proto: {
        changeVal() {
          const { $data } = this;

          setTimeout(() => {
            $data.val++;
          }, 200);
        },
      },
    };
  </script>
</template>

```

**Comment by fightwithtiger** [comment]
> 其实不建议在fill项中直接绑定host函数。如果要绑定，首先要获取'$index'和'$data'，减少'this'的使用，让代码更加简洁直观。
> 
> ```
> <template component>
>   <x-fill :value="counts">
>     <div class="item" on:click="$host.changeVal">
>       $index : {{$index}}; $data : {{$data}}
>     </div>
>   </x-fill>
> 
>   <br />
>   <br />
> 
>   <x-fill :value="counts">
>     <div class="item" on:click="$host.changeVal2">
>       $index2 : {{$index}}; $data2 : {{$data}}
>     </div>
>   </x-fill>
>   <script>
>     export default {
>       data: {
>         counts: [0, 0, 0],
>         counts2: [0, 0, 0],
>       },
>       proto: {
>         changeVal() {
>           const { $index, $host } = this;
> 
>           setTimeout(() => {
>             $host.counts[$index] = $host.counts[$index] + 1;
>           }, 200);
>         },
>         changeVal2() {
>           const { $index, $host } = this;
>           $host.counts[$index] = $host.counts[$index] + 1;
>         },
>       },
>     };
>   </script>
> </template>
> ```

I argee with you, useually we get parameters by deconstructing. This problem occurs whenever there is asynchrony, but not everyone will always remember to use this approach, especially in a form like vue2-options-api. If the parameter is passed, it will appear very intuitive, reducing the workload in this area.

**Comment by kirakiray** [comment]
thank you for your feedback

Because the binding function follows the native JavaScript method, the native Event object is passed. Including the 'this' pointer, according to native JavaScript, should point to the trigger object itself. Like this:

```javascript
    const A = {
      val: "I am A",
      childs: [
        {
          val: "I am sub1",
        },
        {
          val: "I am sub2",
        },
      ],
      func() {
        console.log(this.val);
      },
    };
    A.func();

    const sub1 = A.childs[0];
    sub1.func = A.func;
    sub1.func();
```

The direction of ofa.js is to expand the browser operating environment and try to be as close to the browser's native writing method as possible.

If the binding function in the fill is changed to pass parameters, then the event binding of elements outside the fill will also be changed to this rule. This change is too big, but the benefit is not big. You can use `on:click="$host.changeVal({$index, $data})"` instead. So this point may not change for the time being.
