### ISSUE TITLE
Hope to support for finer grained updates

### ISSUE THREAD

**Issue by fightwithtiger** [kirakiray/ofa.js#129]
I found that when a variable in data changed, the template expression in the entire component had to be re-executed.
For example: 
demo-comp.html
```
<template component>
	{{name}}
	{{counter}}
	<button on:click="add">add</button>
	<script>
		export default {
			data: {
				counter: 0,
				name: 'tom'
			},
			proto: {
				add() {
					this.counter += 1
				}
			},
		};
	</script>
</template>
```

When I click button, expect counter + 1 and update {{counter}} only. But now I found {{name}} update too ！(Even though its content hasn't changed）

I read source code(packages\xhear\render\render.mjs), found this
```
const wid = data.watchTick((e) => {
      if (tasks.length) {
        tasks.forEach((f) => f());
      } else {
        data.unwatch(wid);
      }
    });
```
The tasks are component level, so executing emitUpdate when a variable changes will execute the entire component's render tasks once. Is there room for optimization? For example, the proxy overrides the get method to listen for the corresponding render task on the binding when the variable gets

**Comment by kirakiray** [comment]
Thank you very much for your feedback. You are right, this is a point that needs to be optimized. I optimized it in 4.4.6. You can try updating it: https://cdn.jsdelivr.net/gh/kirakiray/ofa.js@4.4.6/ dist/ofa.min.js

Your case is included in the automated testing of the sub-library at: https://github.com/kirakiray/Xhear/tree/main/test/cases/repeat-render-text

**Comment by fightwithtiger** [comment]
> Thank you very much for your feedback. You are right, this is a point that needs to be optimized. I optimized it in 4.4.6. You can try updating it: https://cdn.jsdelivr.net/gh/kirakiray/ofa.js@4.4.6/ dist/ofa.min.js
> 
> Your case is included in the automated testing of the sub-library at: https://github.com/kirakiray/Xhear/tree/main/test/cases/repeat-render-text

```
const renderFunc = () => {
      const content = func();
      if (textEl.textContent !== String(content)) {
        textEl.textContent = content;
      }
    };
```
It seems like the func still excute every times, if func has some heavy logic, for example:
```
<template component>
	{{renderHeavyLogic()}}
	{{counter}}
	<button on:click="add">add</button>
	<script>
		export default {
			data: {
				counter: 0,
				name: 'tom'
			},
			proto: {
				add() {
					this.counter += 1
				},
				renderHeavyLogic() {
					let sn = ''
					for(let i=0; i<1000000000; i++) {
						sn = i + 1
					}
					return sn
				}
			},
		};
	</script>
</template>
```
when I click add button, page updates slowly. In real business code, the logic of the template in a page is very complex, and the current ofajs's update method can become a performance problem in real applications

**Comment by kirakiray** [comment]
> > Thank you very much for your feedback. You are right, this is a point that needs to be optimized. I optimized it in 4.4.6. You can try updating it: https://cdn.jsdelivr.net/gh/kirakiray/ofa.js@4.4.6/ dist/ofa.min.js
> > Your case is included in the automated testing of the sub-library at: https://github.com/kirakiray/Xhear/tree/main/test/cases/repeat-render-text
> 
> ```
> const renderFunc = () => {
>       const content = func();
>       if (textEl.textContent !== String(content)) {
>         textEl.textContent = content;
>       }
>     };
> ```
> 
> It seems like the func still excute every times, if func has some heavy logic, for example:
> 
> ```
> <template component>
> 	{{renderHeavyLogic()}}
> 	{{counter}}
> 	<button on:click="add">add</button>
> 	<script>
> 		export default {
> 			data: {
> 				counter: 0,
> 				name: 'tom'
> 			},
> 			proto: {
> 				add() {
> 					this.counter += 1
> 				},
> 				renderHeavyLogic() {
> 					let sn = ''
> 					for(let i=0; i<1000000000; i++) {
> 						sn = i + 1
> 					}
> 					return sn
> 				}
> 			},
> 		};
> 	</script>
> </template>
> ```
> 
> when I click add button, page updates slowly. In real business code, the logic of the template in a page is very complex, and the current ofajs's update method can become a performance problem in real applications

Yes, other frameworks will have similar performance issues in this case, and you need to use [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to optimize it.

**Comment by fightwithtiger** [comment]
> > > Thank you very much for your feedback. You are right, this is a point that needs to be optimized. I optimized it in 4.4.6. You can try updating it: https://cdn.jsdelivr.net/gh/kirakiray/ofa.js@4.4.6/ dist/ofa.min.js
> > > Your case is included in the automated testing of the sub-library at: https://github.com/kirakiray/Xhear/tree/main/test/cases/repeat-render-text
> > 
> > 
> > ```
> > const renderFunc = () => {
> >       const content = func();
> >       if (textEl.textContent !== String(content)) {
> >         textEl.textContent = content;
> >       }
> >     };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems like the func still excute every times, if func has some heavy logic, for example:
> > ```
> > <template component>
> > 	{{renderHeavyLogic()}}
> > 	{{counter}}
> > 	<button on:click="add">add</button>
> > 	<script>
> > 		export default {
> > 			data: {
> > 				counter: 0,
> > 				name: 'tom'
> > 			},
> > 			proto: {
> > 				add() {
> > 					this.counter += 1
> > 				},
> > 				renderHeavyLogic() {
> > 					let sn = ''
> > 					for(let i=0; i<1000000000; i++) {
> > 						sn = i + 1
> > 					}
> > 					return sn
> > 				}
> > 			},
> > 		};
> > 	</script>
> > </template>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when I click add button, page updates slowly. In real business code, the logic of the template in a page is very complex, and the current ofajs's update method can become a performance problem in real applications
> 
> Yes, other frameworks will have similar performance issues in this case, and you need to use [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) to optimize it.

Yes, both the mainstream vue and react frameworks have this problem. solid doesn't have this problem, but it does do something in the compile phase to refine granularity. This fine-grained update is also the future direction of optimization. By the way, can 大佬 write an article about the content of web component in xhear on Juejin? Looking at the source code seems to have some way to start。|･ω･｀)

**Comment by kirakiray** [comment]
> Yes, both the mainstream vue and react frameworks have this problem. solid doesn't have this problem, but it does do something in the compile phase to refine granularity. This fine-grained update is also the future direction of optimization. By the way, can 大佬 write an article about the content of web component in xhear on Juejin?Looking at the source code seems a little hard to figure out where to start. |･ω･｀)

Fine-grained optimization may not be possible because there is no compilation process in ofa.js; if this high-CPU-consuming calculation algorithm is done on the main thread, solid will also be stuck, unless solid opens another thread to do function calculations;

Time has been tight recently, and I have been writing projects using ofa.js, as well as trying to solve the problem of eating. Ofa.js has not been paid much attention by anyone for the time being. If I write about its underlying implementation details at this time, the result will definitely be that no one will read it.

In two months, I will update the official website to 4.4. At that time, I will produce an article about the implementation of the underlying details of ofa.js, including content related to modular and component rendering, which will include how to render web components in xhear. .

**Comment by fightwithtiger** [comment]
> > Yes, both the mainstream vue and react frameworks have this problem. solid doesn't have this problem, but it does do something in the compile phase to refine granularity. This fine-grained update is also the future direction of optimization. By the way, can 大佬 write an article about the content of web component in xhear on Juejin?Looking at the source code seems a little hard to figure out where to start. |･ω･｀)
> 
> Fine-grained optimization may not be possible because there is no compilation process in ofa.js; if this high-CPU-consuming calculation algorithm is done on the main thread, solid will also be stuck, unless solid opens another thread to do function calculations;
> 
> Time has been tight recently, and I have been writing projects using ofa.js, as well as trying to solve the problem of eating. Ofa.js has not been paid much attention by anyone for the time being. If I write about its underlying implementation details at this time, the result will definitely be that no one will read it.
> 
> In two months, I will update the official website to 4.4. At that time, I will produce an article about the implementation of the underlying details of ofa.js, including content related to modular and component rendering, which will include how to render web components in xhear. .

Thanks, looking forward to it
