### ISSUE TITLE
如何在子组件中，调用父组件定义的方法

### ISSUE THREAD

**Issue by ihongwu** [kirakiray/ofa.js#137]
请问您一下，如何在子组件中，调用父组件定义的方法，有时候在子组件中执行某类操作后，需用通知父组件执行某个动作，谢谢！

**Comment by kirakiray** [comment]
有两种方式：
1. 通过事件冒泡通知父组件，父组件监听事件：

```html
<template component>
  <!-- 子组件 -->
  ...
  <button on:click="popUp">通知父组件</button>
  <script>
    export default {
      tag: "sub-tag-name",
      proto: {
        popUp() {
          this.emit("custom-event-name", {
            data: {
              value: "data内带上自定义的数据",
            },
            // composed: true, // 这个开启后，会穿透组件的影子层
          });
        },
      },
    };
  </script>
</template>
```

```html
<template component>
  <!-- 父组件 -->
  ...
  <slot></slot>
  ...
  <script>
    export default {
      tag: "parent-tag-name",
      proto: {
        someMethod() {
          // ...
        },
      },
      ready() {
        this.on("custom-event-name", (e) => {
          console.log("接受到的数据: ", e.data);
          // 执行要操作的内容
          this.someMethod();
        });
      },
    };
  </script>
</template>
```

2. 子组件直接运行父组件的方法：

<template component>
  
  ...
  <button on:click="popUp">通知父组件</button>
  <script>
    export default {
      tag: "sub-tag-name",
      proto: {
        popUp() {
          if (this.parent.tag === "parent-tag-name" && this.parent.someMethod) {
            this.parent.someMethod(xxx);
          }
        },
      },
    };
  </script>
</template>

**Comment by kirakiray** [comment]
如果这里的父组件是宿主组件的意思的话，将 parent 改为 host：

```html
<template component>
  <!-- 子组件 -->
  ...
  <button on:click="popUp">通知父组件</button>
  <script>
    export default {
      tag: "sub-tag-name",
      proto: {
        popUp() {
          if (this.host.tag === "parent-tag-name" && this.host.someMethod) {
            this.host.someMethod(xxx);
          }
        },
      },
    };
  </script>
</template>
```

**Comment by ihongwu** [comment]
![image](https://github.com/kirakiray/ofa.js/assets/21274377/03df80df-7bcf-4c87-9c5a-60bae2b244ae)
如您所说，我成功的调用了父组件的方法，但是获取到的tag始终o-page，我在父组件中定义了tag：c-index

父组件截图：
![image](https://github.com/kirakiray/ofa.js/assets/21274377/013dd49a-9259-4ca1-9219-832d502ff0e9)

**Comment by kirakiray** [comment]
哦哦，如果是 page模块的话，你给对应的 page 定一个私有属性，确保是目标page就好；

```html
<template page>
  <!-- 父页面 -->
  ...
  <script>
    export default {
      data: {
        markId: "Iam page 1",
      },
      proto: {
        someMethod(xxx) {
          // ...
        },
      },
    };
  </script>
</template>
```

```html
<template component>
  <!-- 子组件 -->
  ...
  <button on:click="popUp">通知父页面模块</button>
  <script>
    export default {
      tag: "sub-tag-name",
      proto: {
        popUp() {
          // 确保父组件是目标组件
          if (this.host.markId === "Iam page 1" && this.host.someMethod) {
            this.host.someMethod(xxx);
          }
        },
      },
    };
  </script>
</template>
```

**Comment by ihongwu** [comment]
> 哦哦，如果是 page模块的话，你给对应的 page 定一个私有属性，确保是目标page就好；
> 
> ```
> <template page>
>   
>   ...
>   <script>
>     export default {
>       data: {
>         markId: "Iam page 1",
>       },
>       proto: {
>         someMethod(xxx) {
>           // ...
>         },
>       },
>     };
>   </script>
> </template>
> ```
> 
> ```
> <template component>
>   
>   ...
>   <button on:click="popUp">通知父页面模块</button>
>   <script>
>     export default {
>       tag: "sub-tag-name",
>       proto: {
>         popUp() {
>           // 确保父组件是目标组件
>           if (this.host.markId === "Iam page 1" && this.host.someMethod) {
>             this.host.someMethod(xxx);
>           }
>         },
>       },
>     };
>   </script>
> </template>
> ```

明白了，谢谢您
