### ISSUE TITLE
组件内的生命周期，每次都被执行

### ISSUE THREAD

**Issue by ihongwu** [kirakiray/ofa.js#138]
您好，我发现组件内的生命周期（loaded、ready、created等），每次调用都会执行，这在一些场景下会产生问题，比如我在首页加载了一个组件，在组件里面发起了一个数据请求，当我点击跳转到下一个页面，再点击浏览器的返回或者调用ofa的返回，返回到首页，此时我是不希望数据被重新加载的，但是组件的生命周期在这样的场景下同样被执行了，这在vue中不存在这个问题

**Comment by kirakiray** [comment]
你好，感谢你的反馈，你可以将请求操作放在生命周期外，就会只请求一次操作：

```html
<template component>
  ...
  <script>
    const someRequest = fetch("https://xxxx.com/api").then((e) => e.json());

    export default {
      tag: "sub-tag-name",
      async ready() {
        // const data = await fetch("https://xxxx.com/api").then((e) => e.json()); // 每次生命周期都会请求
        const data = await someRequest; // 沿用缓存的初次请求
      },
    };
  </script>
</template>
```

**Comment by ihongwu** [comment]
您好，如您所说，确实达到了效果
![image](https://github.com/kirakiray/ofa.js/assets/21274377/bfd5d7a2-9c7e-49ee-babc-81ae86ff5f8b)

但是还是有一些场景，这种方式不是很合适，比如一个页面的数据，有几个tab，每个tab的数据都不一样，点击tab的时候才会去获取数据，如果在生命周期外先获取所有数据，也会造成资源浪费，并且还会有分页，搜索等不同场景。

如果生命周期也像vue那样只执行一次，或提供一个只执行一次的周期的话，那样就能彻底解决这个问题。

不然实际生产中，场景很复杂，感谢！

**Comment by kirakiray** [comment]
> 您好，如您所说，确实达到了效果 ![image](https://private-user-images.githubusercontent.com/21274377/320176867-bfd5d7a2-9c7e-49ee-babc-81ae86ff5f8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODM5NzMsIm5iZiI6MTcxMjM4MzY3MywicGF0aCI6Ii8yMTI3NDM3Ny8zMjAxNzY4NjctYmZkNWQ3YTItOWM3ZS00OWVlLWJhYmMtODFhZTg2ZmY1ZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA2MDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzQ1ZmM3Yjc2MDcyY2VlYjA5ZWI4MTA2Y2FkZmVmMzZmNTQ3YWE5MmI0YTgxNzIwNmEyNDhkNjg3M2JkZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oAJCVILIQtZwIbc4GhX7SGAkj-a7TrnfZxPpEaIS5vs)
> 
> 但是还是有一些场景，这种方式不是很合适，比如一个页面的数据，有几个tab，每个tab的数据都不一样，点击tab的时候才会去获取数据，如果在生命周期外先获取所有数据，也会造成资源浪费，并且还会有分页，搜索等不同场景。
> 
> 如果生命周期也像vue那样只执行一次，或提供一个只执行一次的周期的话，那样就能彻底解决这个问题。
> 
> 不然实际生产中，场景很复杂，感谢！

如果是tab的话，可以请求数据的逻辑下手；这里简单更壮一个 getData方法：

```javascript
const obj = {};
export const getData = async (tabId) => {
  let targetPms = obj[tabId];

  if (!targetPms) {
    switch (tabId) {
      case "home":
        targetPms = fetch("https://xxxx.com/api/home").then((e) => e.json());
        break;
      case "setting":
        targetPms = fetch("https://xxxx.com/api/setting").then((e) => e.json());
        break;
    }

    obj[tabId] = targetPms;
  }

  return targetPms;
};
```

```html
<template component>
  <select on:change="switchData($event.target.value)">
    <option value="home">Home</option>
    <option value="setting">Setting</option>
  </select>
  ...
  <script>
    export default async ({ load }) => {
      const { getData } = await load("./getdata.js");

      return {
        tag: "sub-tag-name",
        data: {
          list: [],
        },
        proto: {
          async switchData(markId) {
            this.list = await getData(markId);
          },
        },
        async ready() {},
      };
    };
  </script>
</template>
```

感谢你的反馈，会考虑添加一个类似的API，不过可能会先做成第三方库的方式来使用；

**Comment by ihongwu** [comment]
好的，我的场景描述不太准确，如果添加一个只执行一次的生命周期的话，那将会非常棒！
