### ISSUE TITLE
建议增加一个可以加载公共资源的方法

### ISSUE THREAD

**Issue by ihongwu** [kirakiray/ofa.js#139]
您好，建议增加一个可以加载公共资源的方法，比如加载公共的css，目前的解决方法是在每个page和组件内都加载，这看起太累切不优雅，还请考虑下哦！

**Comment by ihongwu** [comment]
比如在公共部位引入某个css，那么在其他的组件或者page中自动加载这个文件

**Comment by kirakiray** [comment]
> 比如在公共部位引入某个css，那么在其他的组件或者page中自动加载这个文件

你的意思只在某个地方配置一次，就所有组件和页面自动添加这个配置的资源吗？如果是的话看看下面的经历：

之前的 ofa.js v3 的版本中就是有 globalcss 功能，因为用起来太方便了，导致被（滥用）添加了大量样式。终于有一天，某个cdn的公用组件shadow内的 class name 和 globalcss 命名重复导致样式冲突，然后花了好大成本重新规范代码。（其实初衷就是为了少写工用样式代码，修改 a 标签之类的默认样式）

后面又添加了一个 globalcss 作用域的配置选项，尝试解决这个问题。研究后发现是挖新坑补旧坑，所以功能代码直接舍弃了。在 v4 后就彻底抛弃了 globalcss 的配置选项了 😂。

> 比如加载公共的css，目前的解决方法是在每个page和组件内都加载，这看起太累切不优雅，还请考虑下哦！

这个问题其实好解决。可以先定义一个 `public.css`，和这个公用样式相关的组件和页面，就添加一个link标签引用这个 public.css 资源。

如果公用样式也是管理好并分组的，可以在 public.css 里面使用 [@import](https://www.runoob.com/cssref/pr-import-rule.html) 语法引用分组的样式，那么从组件和page内看起来，只会引用 public.css 一个资源而已。

希望这个回复能帮到你。

**Comment by ihongwu** [comment]
globalcss我觉得这个非常好呀，如果直接舍弃的话，有点可惜！

如果可以配置globalcss，这样既可以使用组件式开发，又可以享受到普通css的方便

在大的项目中，每个组件都link一下public.css确实不太优雅，有点累人，这个比较印象技术选型！

关于冲突的问题，可以定义一个不生效的组件，定义以后符合条件的组件就不自动加载！

**Comment by kirakiray** [comment]
好的，已添加 globalcss 的提案，后续会重新思考更和谐的使用方式，

**Comment by ihongwu** [comment]
非常感谢，等待更新!
