### ISSUE TITLE
Support global style or css

### ISSUE THREAD

**Issue by kirakiray** [kirakiray/ofa.js#140]
globalcss我觉得这个非常好呀，如果直接舍弃的话，有点可惜！

如果可以配置globalcss，这样既可以使用组件式开发，又可以享受到普通css的方便

在大的项目中，每个组件都link一下public.css确实不太优雅，有点累人，这个比较印象技术选型！

关于冲突的问题，可以定义一个不生效的组件，定义以后符合条件的组件就不自动加载！

_Originally posted by @ihongwu in https://github.com/kirakiray/ofa.js/issues/139#issuecomment-2041117422_

**Comment by FalconWu2017** [comment]
是的哦，一般网站都会有个全局型的css对整体做个初步的页面样式，这样非常方便。具体某个组件有特殊样式要求在组件内自己定义也可以满足个性化要求。   
其实大部分网站应该都是全局定义的。

**Comment by kirakiray** [comment]
已添加 `global-link` 组件，你可以查阅相关文档进行使用。

* 使用方法：https://github.com/kirakiray/ofa.js/blob/main/libs/global-link/readme-cn.md
* 测试代码：https://github.com/kirakiray/ofa.js/blob/main/libs/global-link/test/test.html
* 测试代码在线预览：https://kirakiray.github.io/ofa.js/libs/global-link/test/test.html
