### ISSUE TITLE
出现获取组件为null的问题，是我使用方式不正确吗？

### ISSUE THREAD

**Issue by attsion** [kirakiray/ofa.js#145]
![屏幕截图 2024-04-26 174456](https://github.com/kirakiray/ofa.js/assets/3921596/ad7c072e-58e3-4a6e-81f6-2ce6eab3ebe9)
补充：在ready、attached回调里打印仍然为null

**Comment by kirakiray** [comment]
ofa("#divtest") 查找的是 body下的 `[id="divtest"]` 元素；查找组件内的元素，在 ready 内用 `this.shadow.$('#divtest')` 查找，因为这是渲染在组件内影子节点内，和 body 是隔离开的。

https://ofajs.com/cn/api/instance/shadow.html

**Comment by attsion** [comment]
> ofa("#divtest") 查找的是 body下的 `[id="divtest"]` 元素；查找组件影子节点内的元素，在 ready 内用 `this.shadow.$('#divtest')` 查找，因为这是渲染在组件内影子节点内，和 body 是隔离开的。
> 
> https://ofajs.com/cn/api/instance/shadow.html
感谢回复，我按文档首页那种方式试了好多次，没注意组件模式和普通模式的区别，受教了
