### ISSUE TITLE
ofa的组件页面中无法使用其他web components？

### ISSUE THREAD

**Issue by dongnanyanhai** [kirakiray/ofa.js#148]
想要用ofa.js搭配下面这个shoelace-style使用，发现shoelace-style的组件在ofa的组件页面不会被渲染。

搜了一圈没找到解决方案，请问ofa组件中能使用其他web components吗？

**Comment by kirakiray** [comment]
我试了下能够被渲染，请问你能详细描述一下你的问题吗？

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>测试使用 shoelace</title>
    <script src="https://cdn.jsdelivr.net/gh/kirakiray/ofa.js@4.4.5/dist/ofa.min.js"></script>
    <!-- 按照官方的用法，将下面两个库直接加载 -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/themes/light.css"
    />
    <script
      type="module"
      src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/shoelace-autoloader.js"
    ></script>
  </head>
  <body>
    <sl-button>Click me</sl-button>
    <o-page src="./page-one.html"></o-page>

    <br />

    <!-- 加载 wrap-btn 按钮 -->
    <l-m src="./comps/wrap-btn.html"></l-m>
    <wrap-btn>我是二次包裹的按钮</wrap-btn>
  </body>
</html>
```

<img width="705" alt="image" src="https://github.com/kirakiray/ofa.js/assets/5945154/175e261e-d1c3-4087-b211-18d932902243">

**Comment by kirakiray** [comment]
兄弟我懂你的意思了，我尝试了一下比较正式的场景中使用 `shoelace-style`，也发现无法加载组件的问题，问题出在 [`shoelace-autoloader.js` 文件](https://[cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/shoelace-autoloader.js](https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/shoelace-autoloader.js)上，它会监听body上使用了哪些组件，再进行自动加载使用过的组件。而在 web components 影子节点内使用 shoelace 的话，它就没办法监听到使用了哪些组件，所以才没有被渲染。

所以你要改用主动引用组件的方式来使用，比如[使用按钮组件](https://shoelace.style/components/button#importing)，现在下方主动引用仓库后在使用，例如：

```html
<template component>
  <l-m src="@shoelace/button/button.js"></l-m>
  <sl-button>
    <slot></slot>
  </sl-button>
  <script>
    import 'https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/components/button/button.js';
    export default async ({ load }) => {
      return {
        tag: "wrap-btn",
      };
    };
  </script>
</template>
```

**Comment by kirakiray** [comment]
当然，我建议你先在全局上通过 [lm.config](https://ofajs.com/cn/cases/alias.html) 方法设置别名，这样使用会更接便捷，代码如下：

```html
<script>
// 定义快捷路径
      lm.config({
        alias: {
          "@shoelace":
            "https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.15.1/cdn/components",
        },
      });
<script>
```

在 ofa.js 组件上使用时就能通过l-m更简短清晰的使用：

```html
<template component>
  <l-m src="@shoelace/button/button.js"></l-m>
  <sl-button>
    <slot></slot>
  </sl-button>
  <script>
    export default async ({ load }) => {
      return {
        tag: "wrap-btn",
      };
    };
  </script>
</template>
```

下面我附赠一份测试代码，已经能完美运行。（要在静态服务器下打开）

[use-in-shoelace.zip](https://github.com/user-attachments/files/15526343/use-in-shoelace.zip)

**Comment by dongnanyanhai** [comment]
[use-in-shoelace.zip](https://github.com/user-attachments/files/15526343/use-in-shoelace.zip)确实可以，非常感谢！

**Comment by dongnanyanhai** [comment]
别名这个功能特别有用，感谢！
