### ISSUE TITLE
能否纯本地使用？

### ISSUE THREAD

**Issue by Object1805** [kirakiray/ofa.js#164]
最近有个想法，想通过打包前端文件，实现由纯前端构成的单机应用，当我了解到ofa.js，简直欣喜若狂，太符合我的预期，但是在部署时候遇到一个致命的问题，就是file协议无法像http协议，那样提供给src属性进行访问，想请教作者，有没有方法可用处理跨域访问的问题；或者调整成在同一个文件里进行src属性设置，避免出现跨域问题。这样可能更能带动小项目的应用。

**Comment by kirakiray** [comment]
你好，这个需求是可以实现的，不过有几个前置问题问一下：
* 是不是想要一个打包工具，选择本地的ofajs应用打包，就变成一个html，直接双击这个html，让浏览器运行这个应用？
* 在使用 ofa.js 开发web应用的时候，你有没有在本地搭建http静态服务器？需不需提供辅助静态服务器功能？
* 能不能接受下面的交互方式：打开一个网页，然后选择一个使用ofa.js 开发好的应用，在这个域名下运行应用。

**Comment by Object1805** [comment]
您好，您提供的运行器确实是一个好建议，能够在无服务器的状态下运行，是目前最好的解决方案；我原本的想法是跟你第一个建议是一样，在浏览器中使用直接使用html+js便可用完成指定的任务，但是经过实践后发现，这个方案除非是使用原生的js脚本模式，只要涉及到模块化，基本无法摆脱跨域问题；感谢你的帮助和解答！

**Comment by kirakiray** [comment]
> 您好，您提供的运行器确实是一个好建议，能够在无服务器的状态下运行，是目前最好的解决方案；我原本的想法是跟你第一个建议是一样，在浏览器中使用直接使用html+js便可用完成指定的任务，但是经过实践后发现，这个方案除非是使用原生的js脚本模式，只要涉及到模块化，基本无法摆脱跨域问题；感谢你的帮助和解答！

是的，在launcher上运行的话，拥有完整的api权限，例如fetch， File Access API，摄像头麦克风，剪贴板api 等等，应用更加全面。建议1的打包器也在计划当中，不久将来也会提供这个打包工具，支持双击在file协议上运行（不过file协议下很多api无法使用，并且要抛弃 import 语法，全面改用 load 函数进行加载）。
