### ISSUE TITLE
emit 传 false 收到的是 undefined

### ISSUE THREAD

**Issue by lhf6623** [kirakiray/ofa.js#174]
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/6e605641-b52b-4ad5-9723-f725dd0dffc9">
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/00c96d7c-e1bf-4e5f-a865-1444a5d6c6fd">

**Comment by kirakiray** [comment]
这貌似是一个bug，内部判断到 `!data` 时候不做处理，稍等我改一下bug

**Comment by kirakiray** [comment]
已修复问题，请将 ofajs 资源更新到 4.5.20 即可；

```html
<script src="https://cdn.jsdelivr.net/gh/kirakiray/ofa.js@4.5.20/dist/ofa.min.js"></script>
```

**Comment by kirakiray** [comment]
官网已做对应更新：

https://ofajs.com/cn/cases/event-passing.html

**Comment by lhf6623** [comment]
> 官网已做对应更新：
> 
> https://ofajs.com/cn/cases/event-passing.html

这么快速

**Comment by kirakiray** [comment]
> > 官网已做对应更新：
> > https://ofajs.com/cn/cases/event-passing.html
> 
> 这么快速

是的，因为我也在用，有bug肯定先修，所以放心食用。
