### ISSUE TITLE
Can i use this in production now or in development for test.

### ISSUE THREAD

**Issue by chnkarl** [kirakiray/ofa.js#81]

**Comment by kirakiray** [comment]
This framework is safe to use in a production environment. It has been applied and iterated over a long period of time on the official website and has stood the test of time. However, it is important to note that there may be some issues as the framework is still in a rapid development phase. If you encounter any problems, you can give us the first feedback and we will deal with them promptly.

**Comment by chnkarl** [comment]
appreciate your answer. i think i can use it in my product, thanks again



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 1, 2023 20:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kirakiray/ofa.js] Can i use this in production now or indevelopment for test. (Issue #81)




 
This framework is safe to use in a production environment. It has been applied and iterated over a long period of time on the official website and has stood the test of time. However, it is important to note that there may be some issues as the framework is still in a rapid development phase. If you encounter any problems, you can give us the first feedback and we will deal with them promptly.
