### ISSUE TITLE
what does ofa mean?

### ISSUE THREAD

**Issue by chnkarl** [kirakiray/ofa.js#82]

**Comment by kirakiray** [comment]
One For All

**Comment by pengchenggang** [comment]
After reading your docs, I was looking for what OFA meant, and since it wasn't stated on your docs, I had to go here and finally found it. I think your ofa is very good, support you!

**Comment by kirakiray** [comment]
> After reading your docs, I was looking for what OFA meant, and since it wasn't stated on your docs, I had to go here and finally found it. I think your ofa is very good, support you!

Thank you for your support
