### ISSUE TITLE
This one is more easy to understand than lit, but template engine tags should be more common, eg: o-for o-if, ithink is better than x-if 

### ISSUE THREAD

**Issue by chnkarl** [kirakiray/ofa.js#84]

**Comment by kirakiray** [comment]
There is actually some historical background to this, and I also considered this initially. ofa.js was developed on the basis of three sub-libraries: [stanz](https://github.com/kirakiray/stanz) is responsible for data synchronization, [xhear](https://github.com/kirakiray/xhear) handles the core component encapsulation logic, and [drill.js](https://github.com/kirakiray/drill.js) deals with modular data processing. Components starting with `x-` inherit from `xhear`, while `x-` and `o-` prefixed components have their respective roles. `x-` represents components that can only be used within templates, such as `x-if` and `x-fill`, whereas components starting with `o-` are more independent entities, like `o-page` and `o-app`. The use of `x-` and `o-` clearly distinguishes the responsibilities of these two types of components. If we were to unify them as `o-`, it might appear more consistent, but in practice, it could lead to errors, such as mistakenly using `o-if` outside of templates.
