### ISSUE TITLE
网络请求能写个例子吗？GET POST

### ISSUE THREAD

**Issue by ieras** [kirakiray/ofa.js#93]
网络请求能写个例子吗？GET POST

**Comment by kirakiray** [comment]
ofa.js 内不包含网路请求的功能，可以使用 fetch API 请求网络；

**Comment by kirakiray** [comment]
使用 [fetch API ](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API/Using_Fetch)来请求数据，可以在 ready 或者 attached 周期添加数据。这里写个 GET 的方式：

```html
<template page>
  ...
  <script>
    export default {
      data: {
        list: [],
      },
      async ready() {
        const data = await fetch("xxxx/api").then((e) => e.json());

        this.list = data;
      },
    };
  </script>
</template>
```

https://www.ruanyifeng.com/blog/2020/12/fetch-tutorial.html
