### ISSUE TITLE
建议能结合layui3.x

### ISSUE THREAD

**Issue by minsishuju** [kirakiray/ofa.js#94]
从介绍上来看，趋势比jq有优势，
layui 也算是在jq上的UI，现在依然很活跃，也有很多人再用，建议可以跟layui结合一下，相信能帮助彼此加快发展的。
[@layui](https://github.com/layui/layui)
比如将layui中使用的jq 换成ofajs。。。

**Comment by kirakiray** [comment]
感谢你的反馈，后面会考虑出过渡方案，也会有教程，但最终还是以替换为 ofa.js 为主展开的。
