### ISSUE TITLE
关于传统的前端框架和 ofa 结合使用

### ISSUE THREAD

**Issue by haobarry** [kirakiray/ofa.js#98]
如题,  想把现有的vue或react框架改造和ofa结合使用, 或者把vue项目引入ofa.  
可否有个例子, 参考一下, 谢谢

**Comment by kirakiray** [comment]
感谢你的留言，我们会安排这个教程。

**Comment by kirakiray** [comment]
这里先弄了一个 Vue 中使用 ofa.js 的仓库。

**Comment by haobarry** [comment]
> 这里先弄了一个 Vue 中使用 ofa.js 的案例。
> 
感谢

**Comment by kirakiray** [comment]
又加了个React的教程，React支持更好，配置更少。
